### ISSUE TITLE
Reset not working

### ISSUE THREAD

**Issue by martinpelli** [ngocvuphan/flutter_web_date_picker#1]
Clicking reset  button is not doing anything. 

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale en-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!`

**Comment by martinpelli** [comment]
Reset is working but not as expected I thought it will be used for reseting the form text, but instead is just for going to first date, so there is no way to clear/reset the input, also it would be nice an option to hide reset and today buttons as they are not useful for me

**Comment by ngocvuphan** [comment]
updated doc and added features
