### ISSUE TITLE
Customizing colors for selected month and year

### ISSUE THREAD

**Issue by Alzobair50** [ngocvuphan/flutter_web_date_picker#11]
Hi, I'm using this package and I'm able to update selected day, confirm, cancel text colors like below:

![image](https://github.com/user-attachments/assets/bc21530a-9ce9-459c-8f4f-cdb2874b3bd2)

is there to update the color of the selected year and selected month.

![image](https://github.com/user-attachments/assets/92f89c41-52d1-471c-8e64-dea48e8c1c6d)

**Comment by ngocvuphan** [comment]
Please use 'selectedDayColor' for the selected color in all views
