### ISSUE TITLE
Bug Report: Date Picker Overflow if the Field Size is Small

### ISSUE THREAD

**Issue by mu7mmd** [ngocvuphan/flutter_web_date_picker#12]
**Description**
The date picker widget overflows if the field size is small. Instead of overflowing, the date picker should overlay the parent widget with no size restriction.

![Screenshot 2024-12-29 104037](https://github.com/user-attachments/assets/6804444b-6eeb-465e-ba24-d53b2076809c)

**Expected Behavior**
The date picker should overlay properly without size constraints, regardless of the parent field size.

**Current Behavior**
The date picker overflows when the field size is small.

**Steps to Reproduce**
1. Use `flutter_web_date_picker `in a Flutter app.
2. Set a small width for the parent field.
3. Open the date picker.

**Environment**
Flutter version: 3.24.5
Package version: `vph_web_date_picker: ^0.1.1`

**Suggested Fix**
Introduce a width parameter for the date picker:
- If width is null, use the parent size as the default.
- If width is specified, use the provided width size.

**Comment by ngocvuphan** [comment]
Already have the 'width' parameter. Please check the example for details.
