### ISSUE TITLE
Locale support missing?

### ISSUE THREAD

**Issue by matteoberla** [ngocvuphan/flutter_web_date_picker#2]
Hi, is app locale supported? 
I've set locale as it_IT on the app but i see the english calendar.

I also need to be able to choose the order of days, now it's Sun...Sat but i need Mon...Sun.

**Comment by ngocvuphan** [comment]
Using firstDayOfWeekIndex=1 to set Monday is first day of week.
Currently, the package does not support localization. We will add it in the future!

**Comment by matteoberla** [comment]
Where do i set that property?
How long will it take to implement Locale support?

**Comment by ngocvuphan** [comment]
check latest version for update

**Comment by matteoberla** [comment]
Thank you very much
