### ISSUE TITLE
Change style of widget

### ISSUE THREAD

**Issue by matteoberla** [ngocvuphan/flutter_web_date_picker#3]
Hi, 

how can i change the primary color of the widget?
how can i set the month first letter to be capitalized?
how can i prevent the user to change manually the text inside the textfield?

thank you

**Comment by ngocvuphan** [comment]
For your questions, please refer to the provided example code:
1. Using the ThemeData to set the primary color.
2. The first character of the month is already capitalized.
3. The text field within the example is already set to unmodifiable.

**Comment by matteoberla** [comment]
I need to set a color for the current day, one for the selected day and different color for confirm buttons

Month is lowercase, tomorrow I'll provide some photos 

I can modify the textfield with your example but setting read only fixed my problem

**Comment by matteoberla** [comment]
Lower case month
![lowercase](https://github.com/user-attachments/assets/a821b2a0-7ca0-4b00-b4c6-c549af702112)

i can write on the field
https://github.com/user-attachments/assets/0c3eed0e-6b5f-4315-89be-ce6323b7c68e

code copied and pasted from [pub.dev](https://pub.dev/packages/vph_web_date_picker):
```
Padding(
            padding: const EdgeInsets.all(8.0),
            child: Container(
              width: 300,
              child: TextField(
                key: textFieldKey,
                controller: _controller,
                onTap: () async {
                  final pickedDate = await showWebDatePicker(
                    context: textFieldKey.currentContext!,
                    initialDate: _selectedDate,
                    firstDate: DateTime.now().subtract(const Duration(days: 7)),
                    lastDate: DateTime.now().add(const Duration(days: 14000)),
                    //width: 300,
                    //withoutActionButtons: true,
                    //weekendDaysColor: Colors.red,
                    //firstDayOfWeekIndex: 1,
                  );
                  if (pickedDate != null) {
                    _selectedDate = pickedDate;
                    _controller.text = pickedDate.toString();
                  }
                },
              ),
            ),
          )
```

colors are still a problem as they are not customizable

**Comment by matteoberla** [comment]
Any news on the color customization and uppercase month?

**Comment by ngocvuphan** [comment]
I have no plans to update the code in the next short time. Please feel free to update the code and add your desired features.

**Comment by matteoberla** [comment]
I'll use another package. Thank you
