### ISSUE TITLE
Customisable "asDropDown" for "showWebDatePicker" function

### ISSUE THREAD

**Issue by KamilSztandur** [ngocvuphan/flutter_web_date_picker#5]
Hey,

I really enjoy your package but I wonder if you could add possibility to customise `asDropDown` flag for `showWebDatePicker` method. In my case I don't want the calendar to be glued to the bottom edge of the screen but to align in the very center instead.

Example:
```dart
final result = await showWebDatePicker(
  context: context,
  initialDate: DateTime.now(),
  asDropDown: false,
);
```

**Comment by ngocvuphan** [comment]
Do you mean the picker shown as a popup dialog?
