### ISSUE TITLE
Dates are doubled across daylight savings time

### ISSUE THREAD

**Issue by jbwise** [ngocvuphan/flutter_web_date_picker#6]
With daylight savings time next month, I see two November 3s in the calendar control.  I was able to resolve this by adding .toUtc() in a few places...

Line 129 of web_date_picker.dart
_selectedDate = _startDate = widget.initialDate.toUtc();

Line 24 of extensions.dart
DateTime start = DateTime(year, month).toUtc();

Lines 30, 31 of extensions.dart
? start.add(Duration(days: numberCellsOfMonth)).toUtc()
: DateTime(year, month + 1, 0).toUtc();

I believe with dates in dart, you should always use UTC values instead of localized to avoid issues like doubling up dates since the .add() adds 86,400 seconds instead of incrementing the date.

**Comment by ngocvuphan** [comment]
FIXED per suggestion. Thanks!!!
